### ISSUE TITLE
Issues/comments found during implementation

### ISSUE THREAD

**Issue by Jakuje** [simo5/ietf#16]
* The section 5.1, step 5 says, that the MIC is computed, but is missing information that it should be sent to the client (C). The sending part is completely omitted here. The previous RFC with DH GSSAPI key exchange has the following sentence:

> S then sends f and the message integrity code (MIC) to C.

We should cover something similar, such as

> S then sends Q_S and the message integrity code (MIC) to C.

as the last step of this point.

* Another potential issue is that `SSH_MGS_KEXGSS_INIT` and `SSH_MGS_KEXGSS_COMPLETE` message (and others in ECDH) have different semantics than in the RFC 4462 (substituting BIGNUM with string) for the public key part. I am not sure if this is common practice or if that can cause some problems (when we got into this stage, both client and server should be ready to accept them).

---
Anyway, I put together a patch set implementing the minimum of recommended algorithms (so far), so a review/comments would be welcomed, before I will move them to Fedora:

https://github.com/Jakuje/openssh-portable/commit/6ec6181 (DH: trivial)
https://github.com/Jakuje/openssh-portable/commit/d945411 (ECDH: a lot of new code)

Testing showed that I was able to connect using these methods.

**Comment by tomato42** [comment]
> Another potential issue is that SSH_MGS_KEXGSS_INIT and SSH_MGS_KEXGSS_COMPLETE message (and others in ECDH) have different semantics than in the RFC 4462 (substituting BIGNUM with string) for the public key part. I am not sure if this is common practice or if that can cause some problems (when we got into this stage, both client and server should be ready to accept them).

I don't know either, I'd expect it not to matter as at the point you are parsing them, you already know which key exchange method you're handling - and even then, interpreting string as a bignum should not cause any loss of information...

**Comment by simo5** [comment]
@jakuje, are you still waiting for feedback on the 2 commits?
It's be easier if you made a PR out of them against your own master I think ...

**Comment by Jakuje** [comment]
The referenced commits were already reviewed and are in Fedora 27 OpenSSH package (though the new methods are still disabled by default waiting for the draft to be published) [1]. But second pair of eyes are always welcomed. Current commits are on top of the master in my fork, but should be quite same as the referenced ones -- only rebased on top of upstream.

The changes proposed (and now merged) by Hubert looks good to me. Have it tested that it actually works against some other implementation would be great. I tested it only against itself so far.

I believe we can close this issue if there is nothing more from your side.

[1] https://src.fedoraproject.org/rpms/openssh/blob/master/f/openssh-7.5p1-gssapi-kex-with-ec.patch

**Comment by simo5** [comment]
Sounds like this was resolved
